### ISSUE TITLE
Add core and path type to sciond.get_paths

### ISSUE THREAD

**Issue by mwfarb** [scionproto/scion#1299]
Currently sciond api users are not able to see if the ASes of the returned paths are core or not and what type of link the paths are traversing.
- Modify get_paths() to return the isCore boolean for each ISDAS returned.
- Modify get_paths() to return the link type (peer, parent, child, ...) for each interface pair returned.
- Potentially the topology file if the best place for this the daemon has access to?

**Comment by kormat** [comment]
While it is possible to determine whether an AS is a core or not (by examining the TRC), it's not possible to determine the non-local link types. An app that cares about the core vs non-core can request the relevant TRC via #1297, and get the info that way. We could also add an "isCore" request to sciond, but this seems like a very niche request, and it's probably not worth expanding the API just for this.

**Comment by mwfarb** [comment]
I agree, using the TRC should be sufficient. 

I was also wondering about the paths determination sciond executes during `get_paths`, building a local database of `PathSegmentDB` objects in `core_segments`, `up_segments`, `down_segments`. This could also determine core ASes. However it seems like it might be a misuse of that data. Correct me if I'm wrong, because having an accurate list of segments would make for an awesome visualization. ;-)

**Comment by kormat** [comment]
Oh, actually, `ASInfoReplyEntry` already flags whether an AS is core or not. So that functionality already exists.

You could, in theory, infer the link types between ASes by examining the PathSegments. If you know that an AS is a core, and the next AS is also a core, then that's a core link. If you know that an AS is a core and the next is _not_ a core, then that's a parent->child link. You can identify peering links from the ASEntries in the PathSegment. So, yeah, it is actually possible to do, but it's non-trivial, and something an application would have to do itself. SCIOND does not provide PathSegments to applications, so the application would have to query the path server itself to glean this information, which also has the advantage that the app can get a fuller/more accurate list of segments.
