### ISSUE TITLE
BR: restrict delivery to last AS on path

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1585]
The BR currently will deliver a packet if the destination is the local AS and the path is on the last segment. This is not sufficient to ensure the expected semantics of SCION paths. So, the BR should also ensure that this is the last (routing) AS on the path, or else reject the packet.

**Comment by tklenze** [comment]
Two points:
1. This should only apply to down-segments. For up-segments, the intended semantics is that one can terminate the path before getting to the core.

2. Note that the only sensible definition of "last Hop Field on path" is "the Hop Field's egress interface is set to ⊥ (i.e., a value for 'does not apply')".
If instead you take "last AS on path" to mean that there are no further hop fields, you get nowhere. An attacker could just simply truncate any further hop fields and pretend that any AS is the last AS.

(To me it seems like this issue is essentially a duplicate of issue #1578)

**Comment by kormat** [comment]
I should expand on what i meant by "last _(routing)_ AS". Either:
- This is the last hop field, and it belongs to the destination AS.
- This is the second-last hop field, it belongs to the destination AS, and the last hop field is VERIFY_ONLY.
This is (deliberately) independent of packet direction/segment type, and is somewhat orthogonal to the the policy you were discussing in #1578.

**Comment by kormat** [comment]
Non-exhaustive reasons for doing this:
- It ensures that the destination in the address header and the contents of the path header must agree (or else the packet will get rejected at some point on the path).
- It prevents trailing garbage in the path header that an attacker modify to strip anonymity, or to craft an exploit of parsing code.

**Comment by scrye** [comment]
After the data-plane path/router rework, this should no longer be a problem.
