### ISSUE TITLE
Investigate QUIC behavior in SCION

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1658]
We currently don't have hard data on how QUIC operates on top of SCION, especially regarding MTU issues.

We should collect experimental information about the following:
  - How does SQUIC react to various constant MTUs?
  - How does SQUIC react in response to a change in MTU?
  - How difficult is it to fork the underlying QUIC library to obtain a (maybe) slightly inefficient implementation that is stable enough to allow the client and server to reliably communicate.

The evaluation should be done using the existing SQUIC implementation.

**Comment by scrye** [comment]
This is related to https://github.com/scionproto/scion/issues/1651.

**Comment by lukedirtwalker** [comment]
## Evaluation
### Setup
```
     +--------------------+ 
     | CORE ffaa:0:1      |
     +--------------------+
        /              \
+-----------+       +-----------+
| ffaa:0:2  |       | ffaa:0:3  |
+-----------+       +-----------+
```
### Tests pingpong (S-QUIC, upstream QUIC-go):
`node2$ pingpong -mode server -local 16-ffaa:0:2,[127.0.0.1]:40002 -sciondFromIA`
`node3$ pingpong -mode client -remote 16-ffaa:0:2,[127.0.0.1]:40002 -local 16-ffaa:0:3,[127.0.0.1]:0 -count 10 -sciondFromIA`

Min MTU on node1 that still works: 1183
Min MTU on node3 that still works: 1260

### Tests pingpong (UDP-QUIC, upstream QUIC-go):
Using modified pingpongupd (https://gist.github.com/lukedirtwalker/64f72f763d1f38a4c06d42ac4b555e9f, replace quic-go imports with upstream)
`$ pingpongudp -mode server -local 10.13.0.1:4242 -log.console debug -file /vagrant/random.txt`
`$ pingpongudp -mode client -local 10.13.0.2:4242 -remote 10.13.0.1:4242 -count 10 -log.console debug -file /vagrant/random.txt`
Similar as above below a certain MTU around 1260 pingpong stopped working.

### Tests pingpong (UDP-QUIC, modified QUIC-go):
Using modified pingpongupd (https://gist.github.com/lukedirtwalker/64f72f763d1f38a4c06d42ac4b555e9f)
Using modified QUIC-go (https://github.com/lukedirtwalker/quic-go/commit/b17a2af84ed05b4e7cd1a5060efe4ec7d9b48004)
Works fine with a MTU of 1000, below ping still kind of works but the server reports `[EROR] Unable to read err=EOF` and the end of the pingpong client. So not exactly sure what is going on there.

## Conclusion
* We can patch quic-go to work reliably with lower MTU, using a fixed min value in the code. This should be good enough for the moment for infra.
* An improvement would be that quic-go is able to detect Path MTU instead of using a hardcoded value. (see also: issue 94 upstream)
* The proper solution is TCP
