### ISSUE TITLE
sciond: Refetch should happen asynchronous

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1873]
As of #1872 sciond will refetch segments after a certain amount of time. This could have a weird effect on the client that periodically asks for paths to the same destination, i.e. one sudden spike in the response time.

To not have this situation we should either do this asynchronously (start a go routine at the request)
or maybe even have a specific go routine which does refetching for destination that are used multiple times.

**Comment by scrye** [comment]
Because SCIOND is a proxy, applications should expect queries to SCIOND to sometimes take a long time. If they care about the latency of the query, they should have the asynchronous logic inside their path resolution module.

This would simplify SCIOND logic, and as we've seen in the past, every application is somehow different (e.g., `showpaths` can just block while waiting for paths, while SIGs want to have packages that have some sort of publish/subscribe model).

@lukedirtwalker: what is your opinion on this?

**Comment by lukedirtwalker** [comment]
Yeah let's leave it like it is for now. Once that becomes a problem we can still change the behavior.
