### ISSUE TITLE
lib: Auto reconnecting sciondProxy

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#1974]
Add sciondProxy, which enables transparent reconnects to sciond.

package: `sciondProxy`
<br>

`NewService(sciond.Service, initPeriod, reconnPeriod) sciond.Service`
  returns `service` which implements `sciond.Service`.
<br>

`service`: implements `sciond.Service`
```
type service struct {
  sd sciond.Service
  initPeriod time.Duration
  reconnPeriod time.Duration
}
```
- `service.Connect` returns a `connector`. To that end, it attempts to call `service.sd.ConnectTimeout(1*time.Second)` for the specified initPeriod every second. If no connection is possible in that period, an error is returned.
- `service.ConnectTimeout` has same behaviour, but times out after the specified timeout.
<br>

`connector`: implments `sciond.Connector`
```
type connector struct {
  svc sciond.Service
  conn sciond.Connector
  reconnPeriod time.Duration
}
```
`connector` uses `sciond.Connector` to execute the calls. If an error is indicating that sciond connection is not healthy, the connector will use connector.svc to create a new connection with sciond.
This is done for the reconnection period every second.
<br>
Sample function call:
```
func (c *connector) ASInfo( ia addr.IA) (*ASInfoReply, error) {
    rep, err := c.conn.ASInfo(ia)
    if err == nil {
        return rep, nil
    }
    if err not related to sciond connection {
        return nil, err
    }
    for now in reconPeriod {
        c.conn, err = c.svc.ConnectTimeout(c.reconnPeriod)
        redo call to c.conn
    }
}
```

**Comment by scrye** [comment]
Looks good. The only tricky bit here is that you'll want to ensure that API calls are concurrency safe, so you need to be careful that only one goroutine attempts to reconnect, otherwise you might end up with multiple open connections. You'll want to guard `c.svc.ConnectTimeout` with some sort of mutex.

This is trickier when contexts are involved, as mutexes and contexts don't play well together. You'll probably want a mutex you can select on (you can find an implementation in `go/lib/util.ChannelLock`). This is also mandated by the fact that `XxxCtx` and `Xxx` variants of the same functions can run concurrently, so everything needs to use the channel locks.

Also, you might find the trick in `go/lib/snet/snetproxy/io.go` useful for reducing the amount of boilerplate. Don't know how well it plays though with the many types SCIOND calls can take/return.

**Comment by scrye** [comment]
Also, a global lock on `connector` is not a solution. Some calls can take very long to answer (on the order of seconds for a path request), and it's unfeasible to have all other callers wait for one path segment that is slow to resolve.

**Comment by kormat** [comment]
I'm not actually sure the existing sciond model makes sense, actually. Say you have a an app that's doing multiple path lookups at the same time - the existing lib/sciond will only serve one at a time, right? That doesn't seem desirable. We should probably revert to "one `connect` per query", unless i'm missing something big.

**Comment by scrye** [comment]
Existing `lib/scion` can handle concurrent requests on a single connection.

That being said, having one connection for each exchange is simpler until performance becomes a concern (it's approximately twice as costly as sharing the conn, context-switch wise).
