### ISSUE TITLE
Path server replies exceed MTU

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#2413]
In SCIONLab, we are currently observing that replies to core AS path server requests are hitting message length limits.  The number and length of the available paths simply appears to be too large to fit the reply into a single packet. What we observe is:

* run scmp echo/showpaths in a non core AS to a host in a "far away" ISD
* the local path server requests the core path segments from the core AS path server
    ```
    2019-01-31 09:19:46.546314+0000 [DBUG] [segReqHandler] Received debug_id=4970009d segReq="19-ffaa:0:1304 -> 22-ffaa:0:1601, Flags: {false false}"
    2019-01-31 09:19:46.547061+0000 [DBUG] [segReqHandler] handleCoreDst debug_id=4970009d remote=false
    2019-01-31 09:19:46.547894+0000 [DBUG] [segReqHanlder:fetchCoreSegs] debug_id=4970009d query=19-ffaa:0:1301->22-ffaa:0:1601
    ```
* the core AS path server handles this request, logs
    ```
    2019-01-31 09:19:46.546053+0000 [DBUG] [TRACE] [Messenger] Received message debug_id=d3c3f18b type=SegRequest from="19-ffaa:0:1304,[172.104.242.254]:31043 (UDP)" id=6858740158228426244
    2019-01-31 09:19:46.546116+0000 [DBUG] [segReqCoreHandler] Received debug_id=d3c3f18b segReq="19-ffaa:0:1301 -> 22-ffaa:0:1601, Flags: {false false}"
    2019-01-31 09:19:46.550688+0000 [DBUG] [segReqHandler:handleCoreDst] found segs debug_id=d3c3f18b core=13
    2019-01-31 09:19:46.552064+0000 [DBUG] [segReqHandler] reply sent debug_id=d3c3f18b id=6858740158228426244
     ```
* the reply **packet gets dropped** by the core ASes border router:
    ```
    2019-01-31 09:19:46.552210+0000 [EROR] Error validating packet rpkt=7004729c err=
    >  Total length specified in common header doesn't match bytes received totalLen="11299" actual="9216"
    >      CT: CMNHDR(2):BAD_PKT_LEN(3) Info: Size=9216 MTU=1472
    ```
* the core AS path server logs the SCMP BAD_PKT_LEN
    ```
    2019-01-31 09:19:46.552521+0000 [WARN] error id=2c898c8a goroutine=dispatcher_bck err=
    >  transport error op="RecvFrom"
    >      Class=CMNHDR(2) Type=BAD_PKT_LEN(3) TotalLen=72B Checksum=ab2a Timestamp=2019-01-31 09:19:46.552323 +0000 UTC
     ```
* the request times out in local path server:
   ```
  2019-01-31 09:19:51.548780+0000 [EROR] [segReqHandler] Failed to find core segs debug_id=4970009d err="context deadline exceeded"
   2019-01-31 09:19:51.548831+0000 [DBUG] [segReqHandler] found debug_id=4970009d up=0 core=0
   2019-01-31 09:19:51.549249+0000 [DBUG] [segReqHandler] reply sent debug_id=4970009d id=15343061528412327526
   ```
* scmp echo/showpaths fails
   ```
   2019-01-31 09:19:51.554457+0000 [CRIT] SCIOND unable to retrieve paths ErrorCode="No paths available"
   ```
This problem can be reproduced consistently in the current SCIONLab topology, so we can give you additional debugging information if required.
Note that the configured MTU (1472) is exceeded by a large margin (actual MTU 9KiB); if we'd enforce the configured MTU, I would expect the problem to occur with a lot smaller topologies.

**Comment by matzf** [comment]
Is there a deeper meaning to this 9KiB? At first I thought this is the size of Ethernet jumbo frames, but that would apparently be 9000. More to the point, what would be the consequences of increasing this `pktBufSize` to e.g. `64 * 1024` (max length of a UDP/IPv4 packet)? It seems to me we are relying on IP-fragmentation anyway... 


So we have discussed a few different solutions/workarounds:
* Increase `pktBufSize`, see above. 64KiB would *probably* work for the current SCIONLab topology
* Limit number of paths returned -- simple, except selection criteria?
* Extend the application protocol to allow fragmentation of the data:
   * either on the level of the Path-server (split list of path segments)
   * or split the serialised bytes, e.g. in the Messenger
* Use "a better transport protocol", as you said -- I guess that would mean QUIC? Do you have a rough timeline for this?

Which approach do you think will make most sense?

**Comment by kormat** [comment]
We are currently relying on ip-fragmentation because we don't have an alternative. It's not something we can do long-term (we already have run into a deployment where fragmented packets were dropped silently be the network).

> Increase `pktBufSize`, see above. 64KiB would _probably_ work for the current SCIONLab topology

Increasing pktBufSize will directly increase memory usage by the BR a lot, so bear that in mind if you're constrained by RAM. (i don't remember how much, but i think it's on the order of 3x)

> Limit number of paths returned -- simple, except selection criteria?

As i understand it, you've recently deployed the go PS. The python ps always limited its responses to 5 segments, but currently the go PS does not. So, if it worked before, then making the go PS only return 5 would probably work for you.
Also, we've been doing a lot of work recently on path policies, to allow a query to specify the selection criteria. Support is not yet in the protocol or PS yet, though.

> Extend the application protocol to allow fragmentation of the data:
> * either on the level of the Path-server (split list of path segments)

This could work (though it's a bunch of work, and fundamental changes) for the PS, but not for beaconing, which is where scionlab has traditionally run into the MTU issue.

> * or split the serialised bytes, e.g. in the Messenger

This could work for all cases, but it's even more work and fundamental changes. At that point we're effectively implementing our own transport protocol on top of UDP/SCION.

> * Use "a better transport protocol", as you said -- I guess that would mean QUIC? Do you have a rough timeline for this?

Yeah, QUIC/SCION is the current plan. In theory we plan to have a first version this quarter, but being realistic that might slip a month or two.

**Comment by kormat** [comment]
In the short term i would suggest you start by restricting the number of segments to go PS returns, and if that isn't sufficient for scionlab, then also increase the buffer size on the BR.

**Comment by scrye** [comment]
Now that we use the QUIC protocol to transport RPCs, large messages should no longer be an issue. Is this still a problem?

**Comment by matzf** [comment]
Correct, this is no longer a problem.
