### ISSUE TITLE
daemon: Old IFIDs in Path

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#2467]
The SCION daemon should drop paths/segments (and potentially remove them from the cache) when an Interface ID on the path does not exist (anymore) in the topology file.

**Comment by scrye** [comment]
If an interface ID no longer exists, it will no longer be used for beaconing, meaning now new paths will be created for it. Eventually, all outdated paths will expire and be removed from the Daemon and Control Service path segment caches.

Because the removal of an interface ID is a rare operation, optimizing so that the removal above happens sooner doesn't seem necessary. Also, note that even it the Daemon removed segments containing a local outdated interface ID, it can do nothing about segments containing outdated interface IDs in neighboring ASes, so stale segments can still be returned.

If the segments containing the outdated interface IDs must be deleted immediately (e.g., to avoid seeing them in an application), consider purging path segment databases for all affected ASes.
