### ISSUE TITLE
BS: Add ifid keepalive handler

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2562]

**Comment by matzf** [comment]
In scionlab, we experienced an issue that was caused by IFID packets being queued in the same queue as PCBs (and any other packets). This caused frequent IF-timeouts because IFIDs would be queued behind bursts of thousands of PCBs which would take multiple seconds to be processed, hitting the three second timeout for IFIDs. To fix this, we had to add a fast path for handling IFIDs in the python version of the BS in scionlab. See https://github.com/netsec-ethz/netsec-scion/pull/27.
It would be great if this problem could be adressed here from the beginning (if this even applies to the new architecture).

**Comment by Oncilla** [comment]
The go version will not use the same queue-ing architecture, but rather start a go routine to handle each request. Thus, this should not be a problem anymore.
