### ISSUE TITLE
Make spelling of ifid consistent

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#2639]
Currently, the code-base has various spellings for ifid:
`IfId` vs `IFID` vs `IfID` vs `Ifid`

We should decide on a particular spelling and use that consistently.

**Comment by kormat** [comment]
See also:
- https://github.com/scionproto/scion/wiki/Coding-Guidelines#naming
- https://github.com/scionproto/scion/issues/2923
:cat:

**Comment by mlegner** [comment]
The [guidelines](https://github.com/scionproto/scion/wiki/Coding-Guidelines#naming) imply that only `ifId` and `IfId` should be used for go code. However, bash scripts and python code generally follow different guidelines, e.g., [topo_br_reload_if_ip_acceptance/test](/acceptance/topo_br_reload_if_ip_acceptance/test) or [beacon_server/base.py](/python/beacon_server/base.py). I guess these should be kept in snake_case or UPPER_CASE_SNAKE_CASE; or should they be made consistent with go as well?

**Comment by mlegner** [comment]
Another point: In some places, `intfid`, `IntfID`, etc. is used instead of `IfId`. I guess this should also be changed to `IfId` or `ifId`.

**Comment by kormat** [comment]
@mlegner : I wouldn't worry about bash scripts; and the python code will be deleted as soon as i can convince someone to rewrite the topology generator into a sane language ;)

**Comment by jiceatscion** [comment]
Didn't attempt to rename DB columns.

**Comment by jiceatscion** [comment]
Following ratholing over the PR. I suggest we first agree on what OUR style guide should say. Then I'll fix again the spelling in the code.

The style guide currently says:
"Use IfID or ifID for SCION Interface Identifiers, not IFID or InterfaceID."

From which I extrapolate that IFIDType should be spelled:
"IfIDType".

I think that "If/if" is inconsistent with Go guidelines, since "IF" is an initialism, and that Go guideline about ID is inconsistent with grammar, since it is not an initialism. HOWEVER, I don't really care; we put what we want in our own guidelines and so, the most expedient is to use what's already there, rather than making arbitrary changes.

So anyone really wants to change our guideline about ifid? If not, is my ifidtype extrapolation acceptable?

(Regarding renaming instances of "IfID" to "interface" as part of this PR. I'd rather not address it; it is scope-creep. We can discuss that in another issue if someone wishes to file one.

**Comment by jiceatscion** [comment]
I did not mean that I did not want to change the spelling of "ifId"; I do not want to replace the identifier "ifid" (any casing) with "interface". That wasn't the subject of the Issue and it would require a lot more consideration than search/replace; for example, there are places where the interface isn't an ID, it is a name. There may be places where both concepts are manipulated and so need different names...etc.
