### ISSUE TITLE
gateway: Epochs wrapping over too fast

### ISSUE THREAD

**Issue by sustrik** [scionproto/scion#2948]
Currently, the frame sequence number if 3 bytes long, i.e. epochs wrap over every ~17m packets. At >10GB speed that doesn't amount to much time (single seconds).

We need at least 4 bytes for the sequence number.

**Comment by kormat** [comment]
At 1Tbps, that's ~200B pps. With a 6B sequence number, that wraps every 40 hours. I propose 8 bytes for the sequence number, which means it will wrap after 299 years. That should be future-safe :) In order to accommodate the larger sequence number (and the larger epoch number for #2950), we should move to a 16B sig header.

Proposal:

```
   0B       1        2        3        4        5        6        7
   +--------+--------+--------+--------+--------+--------+--------+--------+
   | Sig Ver| Sess Id|      Index      |               Epoch               |         
   +--------+--------+--------+--------+--------+--------+--------+--------+
   |                               Sequence number                         |
   +--------+--------+--------+--------+--------+--------+--------+--------+
```
We gain a 1 byte field to specify the sig framing protocol version, which would allow us to do transitions in the future.

**Comment by sustrik** [comment]
Let's adopt the proposal in the previous comment with the following modifications:

* rename "epoch" to "stream ID"
* limit it to 20 bits so that it has the same size as flow ID
* keep remaining 12 bits reserved

Additionally, let's remove packet sizes in the payload. Packet size can be inferred from the encapsulated IP header. Not having size field makes implementation of encoding with gather/scatter arrays easier.

Also, let's require that first 40 bytes of the packet (if available) are never split. That would mean that entire static part of the IP header (whether IPv4 or IPv6) can be always read in one go and doesn't have to be reassembled. It also makes encoding implementation rather simple (if there's less than 40 remaning bytes, don't even try to pack next packet into the frame).

**Comment by sustrik** [comment]
Implemented according to kormat's proposal.
