### ISSUE TITLE
gateway: Ambiguous Gateway probes

### ISSUE THREAD

**Issue by sustrik** [scionproto/scion#2973]
At the moment the SIG probe replies are correlated with probe requests only on the session basis. If the path changes between request and reply, the reply via the old path is handled as if it applied to the new path.

Possible solutions:

1. Compare the path in the reply with the current path and dismiss any non-matching probe replies.
2. Put a path hash into the message ID and compare based on that.
3. Keep record of the past N probes and which path they were used for. Dismiss any non-matching probe replies.

**Comment by jiceatscion** [comment]
The only consequence I can think of is that a path failure might be detected a little bit later (i.e. at the next probe), if there was a probe in-flight. I don't see why it is a problem. Since this issue does not describe any hill effect of the approximation. I don't see a need to fix it. Please re-open if there are symptoms or tangible risk thereof.
