### ISSUE TITLE
lib/sock/reliable: expose metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3183]
- dials, dst="ia_local", "isd_local", and "isd_remote", result="err_refused|err_timeout|ok_success|..."
- registers, svc="BS|CS|", result="..."
- reads - number of reads, amount of bytes per read, results
- writes - number of writes, amount of bytes per write, results

for the reconnector subdir:
- timeouts, retries, gauge for current status.

With the unix socket path as a label.

**Comment by scrye** [comment]
I'm not sure I get the `dst` label; there is no SCION destination when dialing to open a reliable socket. The other end is the local SCIOND process, so the address is a UNIX Domain Socket address. Thus `ia_local`, `isd_local`, `isd_remote` does not apply to `Dial`.

**Comment by scrye** [comment]
Regarding reconnecter gauge for current status, all dispatcher sockets will have the same unix socket path (the local dispatcher socket). To uniquely identify a socket, a different label should be used, for example the local registered address:port. However, this is not recommended by Prometheus because it is prone to time series explosion.
