### ISSUE TITLE
reliable.DispatcherService use context instead of 2 methods

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3402]
`reliable.DispatcherService` interface has 2 methods on without timeout one with timeout. We should refactor to a single method which takes a context as first argument.

**Comment by scrye** [comment]
If revisiting this code, also removing Bind Address from the API would be useful.

**Comment by scrye** [comment]
Maybe `ctxAwareConnect` in `go/lib/sciond` is an useful starting point.

**Comment by karampok** [comment]
What do you think:

From
```

	Register(ia addr.IA, public *addr.AppAddr, bind *net.UDPAddr,
		svc addr.HostSVC) (net.PacketConn, uint16, error)
	RegisterTimeout(ia addr.IA, public *addr.AppAddr, bind *net.UDPAddr,
		svc addr.HostSVC, timeout time.Duration) (net.PacketConn, uint16, error)

```
to
```	
Register1(context.Context, addr.IA, *net.UDPAddr, addr.HostSVC) (net.PacketConn, uint16, error)
Register2(context.Context, net.Addr) (net.PacketConn, uint16, error)
```

@scrye @lukedirtwalker

**Comment by scrye** [comment]
I think we can simplify even more. In https://github.com/scionproto/scion/issues/3136#issuecomment-559150305 I suggested:

```
type Dispatcher interface {
    Register(ctx context.Context, registration *snet.UDPAddr, svc addr.HostSVC) (PacketConn, *snet.UDPAddr, error)
}
```

I think there are a few improvements that we can make to that suggestion.

@matzf also suggested we make `svc` a pointer, since that way it's clearer that a user doesn't want to register for SVCs.

Also, I think the returned address is superfluous; it can be extracted easily via `net.PacketConn.LocalAddr`. Also, the address type that we register can be whatever; it's the implementation's job to test that it's supported, and return an error if that is not the case (that is, for what we have right now in `go/lib/sock/reliable`, type assert at registration time and see if it can get a `*snet.UDPAddr`).

Putting it all together, we get:
```
Register(context.Context, net.Addr, *addr.HostSVC) (net.PacketConn, error)
```

What are your thoughts about ^? 

Also, `reliable.DispatcherService` should move to `snet`; moving it where it is used instead of where it is implemented eliminates the risk of import loops, and makes the type ecosystem more straightforward in general (all the basic tools a user interacts with live in `snet`, there implementations may live wherever).
