### ISSUE TITLE
Document breaking changes in a changelog

### ISSUE THREAD

**Issue by ekuiter** [scionproto/scion#3705]
Maybe I overlooked something, but apart from https://github.com/scionproto/scion/releases there does not seem to be a proper changelog.

Especially, there is no overview of breaking changes from one SCION version to the next (e.g., regarding the protocol or external API/flags/TOML configuration of the built executables). This could also be indicated through the use of [semantic versioning](https://semver.org/), which is not done as of now (v0.4.0 to v0.5.0 contains many breaking changes).

**Comment by Oncilla** [comment]
Currently, it is tough to keep track of all breaking changes because we do not have frequent enough releasing. We are working to reduce the time between separate releases, and create them more frequently.

Then we will also be able to keep track of all the breaking changes more easily.

As of now, the version is 0.x.y. According to semantic versioning [anything may change at anytime](https://semver.org/#spec-item-4). But I agree, we should do a better job of announcing what changed to reduce the pain for downstream entities.

**Comment by ekuiter** [comment]
Interesting, didn't know about 0.x.y

**Comment by lukedirtwalker** [comment]
We write more extensive release notes now. An example can be seen here: https://github.com/scionproto/scion/releases/tag/v0.6.0

So I think we can close this.
