### ISSUE TITLE
TLS cert of scion-architecture.net expired

### ISSUE THREAD

**Issue by daenney** [scionproto/scion#3860]
I wasn't sure where to report this.

The TLS certificate on scion-architecture.net has expired, leading to nasty browser warnings. The certificate expired on the 27th of August 2020. I'd highly recommend renewing it and probably configure some monitoring for it.

```
~ ❯❯❯ curl -vvv https://www.scion-architecture.net
*   Trying 129.132.85.42:443...
* Connected to www.scion-architecture.net (129.132.85.42) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by daenney** [comment]
Ping @scrye since you have the most recent activity on this repo.

**Comment by shitz** [comment]
Hi @daenney. Thanks for reporting this. We are not managing the scion-architecture.net domain, but have reported this problem to them on August 28. The people responsible are notified and in the process of getting a new certificate.

**Comment by cmeury** [comment]
@daenney Thanks for reporting this, the root cause for this was a misunderstanding when hosting of the site was handed over to a different internal team. Hosting was taken over, management of the certificate was not. As a result from this incident, we've added alerts to our monitoring system for certificate expiration date so that we're aware well in advance of similar cases in the future. Furthermore the hosting team plans to switch to automated certificate issuance and renewal via Let's Encrypt in the coming months.
