### ISSUE TITLE
Unify path types

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#3872]
Working again on the beaconing static information metadata  (#3779) I observed the number of different types for paths, that are used throughout the system.
There are two main "chains" of type translations (annotated with roughly where the translation is implemented):
- without sciond (in the CS):
  ```
    path segments ---> combinator.Path ---> segutil.path (implements snet.Path)
              combinator           segutil.Router
  ```
- with sciond:
   ```
    path segments ---> combinator.Path ---> sciond.PathReplyEntry ---> sdpb.Paths (transmitted on the wire) ---> sciond.Path (implements snet.Path)
              combinator           sciond/fetcher          server/sciond/grpc                        lib/sciond/grpc
   ```
   In particular, `sciond.PathReplyEntry` is no longer used for anything other than as an intermediate step in this conversion chain.

The two chains result in different structs (`segutil.path` / `sciond.Path`) that almost identically implement `snet.Path`.

## Proposal

* Move `segutil.path` / `sciond.Path` to a share place, e.g. new library `go/lib/path`
* Move translation `combinator.Path -> path.Path` to this new library; alternatively, change the combinator to directly return `path.Path`.
* Change the `segutil.Pather` to return `path.Path`  instead of `combinator.Path` and drop the now redundant `segutil.Router`.
* Drop `sciond.PathReplyEntry`, translate directly from `path.Path` to `sdpd.Paths`

The two chains will then be:

```
    path segments ---> combinator.Path ---> path.Path (implements snet.Path)
              combinator             go/lib/path

    path segments ---> combinator.Path ---> path.Path ---> sdpb.Paths (transmitted on the wire) ---> path.Path (implements snet.Path)
              combinator             go/lib/path  server/sciond/grpc                       lib/sciond/grpc
```

**Comment by Oncilla** [comment]
I like the proposal.
`sciond.PathReplyEntry` only exists for historic reasons, and we did not yet have time to clean this up.

I'm currently rewriting path segments to protobuf, instead of capnp. If you intend to go forward with this proposal please wait until that change is in, because it will touch a lot of places, including path segments, and path combinator. 

After the change, seg.PathSegment will be decoupled from the wire format, which should make a lot things easier and cleaner.
No more capnp structs tainting ~everything.

**Comment by matzf** [comment]
Thanks for the feedback. Ok, I will put this on hold for a bit, thanks for the heads up.
