### ISSUE TITLE
Remove Linux-Only Features

### ISSUE THREAD

**Issue by JonasGessner** [scionproto/scion#4046]
I'm using SCION on Darwin OSes (iOS and macOS) and dispatcher and sciond can be _almost_ compiled straight out of the box if it weren't for one unsupported sycall flag in `underlay/conn.go`: [`MSG_WAITFORONE`](https://github.com/scionproto/scion/blob/master/go/lib/underlay/conn/conn.go#L94)

In this case the affected code can simply be commented out because it appears to be unused anyway. But going forward I suggest removing this specific syscall flag so that dispatcher can be compiled with no modifications on macOS and other OSes that aren't Linux. Surely there must be some way to work without this flag.

Generally it should be avoided to use [OS-specific features such as this `MSG_WAITFORONE` flag](https://man7.org/linux/man-pages/man2/recvmmsg.2.html) – I think it just unnecessarily hurts the possibilities for broader adoption.

**Comment by matzf** [comment]
Which part of SCION are you running on this macOS? This `underlay/conn.go` is (only) used by the router and dispatcher components.

The router and dispatcher use `x/net` library's `ReadBatch`, as this (supposedly) allows to achieve higher throughput. As the [documentation for `ReadBatch`](https://pkg.go.dev/golang.org/x/net@v0.0.0-20210525063256-abc453219eb5/ipv4#PacketConn.ReadBatch) notes, this only uses `recmmsg` on Linux, so this is normally portable: "On Linux, a batch read will be optimized. On other platforms, this method will read only a single message."
Now, setting `MSG_WAITFORONE` is critical when `recvmmsg` is used; otherwise, the call would block indefinitely until the full batch was read which is obviously undesirable when there is a lower rate of incoming packets.
You could move the definition for the flags passed to `ReadBatch`  to a platform specific file (`// +build linux`) to make this more portable.

**Comment by JonasGessner** [comment]
> Which part of SCION are you running on this macOS? This `underlay/conn.go` is (only) used by the router and dispatcher components.

I'm running the full stack, so sciond and dispatcher.

> The router and dispatcher use `x/net` library's `ReadBatch`, as this (supposedly) allows to achieve higher throughput. As the [documentation for `ReadBatch`](https://pkg.go.dev/golang.org/x/net@v0.0.0-20210525063256-abc453219eb5/ipv4#PacketConn.ReadBatch) notes, this only uses `recmmsg` on Linux, so this is normally portable: "On Linux, a batch read will be optimized. On other platforms, this method will read only a single message."
> Now, setting `MSG_WAITFORONE` is critical when `recvmmsg` is used; otherwise, the call would block indefinitely until the full batch was read which is obviously undesirable when there is a lower rate of incoming packets.
> You could move the definition for the flags passed to `ReadBatch` to a platform specific file (`// +build linux`) to make this more portable.

Sounds good to me!
