### ISSUE TITLE
Changes to Dispatcher

### ISSUE THREAD

**Issue by johannwagner** [scionproto/scion#4059]
Hey,

I am currently working on my bachelor thesis for "Improving packet processing speeds on SCION endhosts" at the University of Magdeburg at the chair of Prof. Dr. David Hausheer. We want to evaluate an XDP approach that was already mentioned within #3961 and prototyped by @martenwallewein to raise package processing speeds at SCION end hosts. Therefore, we want to make changes to the current dispatcher. It is one of the main goals of this thesis to upstream the changes to `scionproto`, that future work can be done on this approach.

#3961 mentions, that you do want to remove the dispatcher in the near term.  Therefore I have multiple questions:

**1. Is there a road map for this change?** 
**2. Do you still upstream changes for the dispatcher?** 
**2.1. Would you potentially upstream a change implementing an *optional* XDP accelerated version of the dispatcher?**
We think about an in-place implementation in the existing dispatcher. This would allow us to access the needed information without any problems and provide a drop-in solution for all users of the dispatcher. Also, we want to make sure that the `dispatcher` and the `snet` library are also able to work without an XDP accelerated version for legacy and non XDP compatible environments.
**2.2. Would you potentially upstream a change exposing the application registration information?**
We could also think of a change to expose the needed application registration information to use with an external control binary. We need this information to make sure routing the correct packages to the correct application and passing the packages we do not want to handle to the existing dispatcher.

If you need further information about those changes, feel free to contact me or @martenwallewein (my supervisor).
Thanks in Advance!

Best Regards, 
  Johann

**Comment by shitz** [comment]
Hi @johannwagner. Thanks a lot for your inquiry. See  my answers inline.

> #3961 mentions, that you do want to remove the dispatcher in the near term. Therefore I have multiple questions:
> 
> **1. Is there a road map for this change?**

There is not a specific roadmap yet, but we'd like to get it done in H2 2021.

> **2. Do you still upstream changes for the dispatcher?**
> **2.1. Would you potentially upstream a change implementing an _optional_ XDP accelerated version of the dispatcher?**
> We think about an in-place implementation in the existing dispatcher. This would allow us to access the needed information without any problems and provide a drop-in solution for all users of the dispatcher. Also, we want to make sure that the `dispatcher` and the `snet` library are also able to work without an XDP accelerated version for legacy and non XDP compatible environments.

Given that we plan to drop dispatcher support I don't really see a good chance for this to be upstreamed. This would increase the maintenance burden and also introduce new tech (XDP), which is non-trivial and needs some expertise to maintain. Instead, I propose to implement such a dispatcher in a separate project/repository. We would be glad to link to it from the main README.

> **2.2. Would you potentially upstream a change exposing the application registration information?**
> We could also think of a change to expose the needed application registration information to use with an external control binary. We need this information to make sure routing the correct packages to the correct application and passing the packages we do not want to handle to the existing dispatcher.

Could you elaborate on this further? I don't quite understand what you intend to do here.

-Sam

**Comment by johannwagner** [comment]
Hey, 
thanks for your answer!

Prof. Dr. Hausheer already mentioned within a meeting that we should think about a solution without touching the dispatcher due to its deprecation plans. So we thought about a solution with another control binary, which is not the dispatcher to deploy our XDP approach. As far as we know we need the application registration information to achieve our goal to make sure routing only the correct packages directly to the applications. 
Therefore we thought about a minimal PR introducing the possibility to extract information about application registrations from the dispatcher to utilize them within a control binary for your XDP approach. This can be done by utilizing another UNIX socket or exposing a REST API or adding that information to the Prometheus endpoint.

Best, Johann

**Comment by shitz** [comment]
>Therefore we thought about a minimal PR introducing the possibility to extract information about application registrations from the dispatcher to utilize them within a control binary for your XDP approach. This can be done by utilizing another UNIX socket or exposing a REST API or adding that information to the Prometheus endpoint.

I don't quite understand. My understanding is that in such a setting the dispatcher should be bypassed, i.e., the application does not register with the dispatcher at all. How would you then get the relevant information from the dispatcher?

**Comment by martenwallewein** [comment]
Hey Sam,

thanks for joining the discussion! We do not want to bypass the whole dispatcher with the ebpf approach, but only the packet forwarding logic for particular apps. From #3961, if I understand correctly, the consens is at the moment to let apps open regular UDP ports and to keep the "dispatcher" port 30041 for all incoming SCION packets, to avoid having the port rewriting (copy SCION UDP dest port into UDP dest port so that packets arrive at the applications sockets) done in the border routers. This means, we need a component that does exactly this, which also handles SCMP messages, e.g. port unreachable if a SCION packet arrives having a SCION UDP port that does not match any listening application.

The information we need from the dispatcher is: Which SCION apps are registerend and listen on which UDP ports, so that we can only rewrite ports for those registered SCION applications in ebpf and pass all other packets untouched to the kernel (e.g. those packets that would require sending back SCMP messages, which can not be done in ebpf). This was our intention to put it in the dispatcher for the moment.

So in case our understanding of this forwarding/rewriting is correct, than we would gladly like to help with this aspect to find a solution to which our ebpf approach could later be attached in an easy way. Otherwise, it would be great if we can clarify this. Having the ebpf part outside of the SCION repo is, as mentioned before, also fine for us.

Best,
Marten

**Comment by shitz** [comment]
Hi @martenwallewein 

Thanks for the clarifications. It makes sense to me now.

If we do the port rewriting on the endhost and thus have something akin to the "dispatcher" (let's call it "dispatcher-ng") that wouldn't get any registrations from SCION apps anymore, since the dispatcher-ng would use the L4 information to rewrite the port. How do you imagine this to work with the external utility that installs the EBPF programs? To me it seems that this component would need to get that information from somewhere else.

**Comment by martenwallewein** [comment]
I see, thanks for the response. We got a bit confused with the current state using the dispatcher and the planned state that does not use any app registrations (which removes the dependency to the "dispatcher-ng" and the reconnects, right?) .

To solve this for ebpf without adding app registration, we are currently thinking about fetching open udp ports in the control binary and share this list with the ebpf code, so that we can check if an app is listening behind the SCION udp port for incoming SCION packets. But thats not related to the dispatcher or the dispatcher-ng anymore and will probably be extract completely into a separated component. 

It would be great if we could keep this issue open anyhow for further discussion (maybe we could rename it, because it does not reflect changes to the dispatcher anymore)

**Comment by matzf** [comment]
Hey @martenwallewein, @johannwagner, you do not _have_ to send "Port unreachable" SCMP messages, this is optional. The dispatcher does not currently implement this either, the packets are just silently dropped. I'd suggest to keep it simple, at least for the start, and just ignore open/closed ports in your ebpf component.

**Comment by martenwallewein** [comment]
Hey @matzf, good to know that it's not implemented at the moment. @johannwagner already found a way to keep a list of open ports, so we will be ready once this is implemented in the dispatcher or its successor.

**Comment by oncilla** [comment]
The dispatcher has been dropped in the meantime
