### ISSUE TITLE
router: missing logic for peering links

### ISSUE THREAD

**Issue by nicorusti** [scionproto/scion#4093]
Since moving to the new heaver v2, router's logic cannot handle forwarding on peering links. Specifically, routers cannot discover the other side's interface IDs, therefore no paths across a peering link can be assembled. 

@matzf explained me why: 
"The link liveness used to be checked by "IFID" keep-alive messages sent between the control services of neighboring ASes; these keep-alive messages served the double purpose to announce the local interface ID to the neighbor. For peering links, this remote interface ID needs to be known during beaconing (because the path segments entries will be matched up based on these interface IDs when stitching the path segments together for a peering shortcut).
The new keep-alive mechanism only works on the level of border routers (called bidirectional forwarding detection); the control service was removed from this (which makes a lot of sense!). Now there is no longer any mechanism to announce these interface IDs to be used for beaconing for peering links and so this is now missing. I'm not sure whether there is an existing design to add this missing piece back -- maybe the idea is that this remote interface ID just needs to be supplied in the configuration, idk.
Also, the (open source) router currently just doesn't handle forwarding for the peering link case -- for the "new" header v2, this logic changed significantly and it has not been implemented yet. But here, it's quite clear what would need to be done, I believe. "

**Comment by oncilla** [comment]
Yes, in the legacy keep alive mechanism we involved both the control service and the border routers.
It had multiple responsibilities:
- Keeping the link alive by suppressing revocations.
- Discovering the interface ID of the far-side of each link
- Deciding what peer entries are included in the constructed segments (revoked peer links were ignored)

With the move to the current SCION header design, we drop separated the concerns.
It turned out that knowing the far-side interface ID is only required for the peer links. Regular child and core links do not need this because of the MAC chaining.

Because we have not implemented peer links so far, there also has not been a need for configuring the far-side interface IDs.
However, we discussed this internally some time ago. It is reasonable to just make this a static configuration.
Think about it this way: Changing the interface ID dynamically will result in a lot of stale segments that still reference the old identifier. We do not have a global way of invalidating the caches -> havoc.

Dynamically changing an interface ID would require **very careful** operation. IMO it is far easier to simply create a new interface pair and move traffic to there by stopping to advertise the old interface pair. But even this needs a "don't advertise" mode for an interface pair that we currently do not support in code.

**Comment by benthor** [comment]
Hi @shitz, @oncilla. Unfortunately I am currently not sufficiently familiar with the codebase to easily find the best place to get started with this. In your own best guesstimate, how much work are we talking about? Would it indeed be something that should be manageable as a side project?

**Comment by benthor** [comment]
Okay, so I _did_ get peering to work again, but _only_ on single hop paths with source and destination in directly adjacent peering ASes and without MAC validation. With any longer paths, there are apparently issues related to processing the reverse path.

Here is an incomplete list of the steps I took to get to this point.

* added a `remote_if_id,omitempty` json field to the `BRInterface` struct, allowing for remote interface IDs defined in the `topology.json` files to again be known in the dataplane
* added some logic to `topo.py` to automatically generate the relevant json entry if the interface is marked as a `peer`
* (crudely) propagate this `RemoteIFID` via `topology.go` to `dataplane.go`
* let `validateEgressID()` succeed in case `egress == topology.Peer` 
* disabled path increment in `processEgress()` when `p.infoField.Peer == true` (shot in the dark that helped)
* modified `egressInterface()` to return the proper local peering IF
* lobotomized `verifyCurrentMAC` because peer field validation is apparently somehow different from hop field validation
* fudged `GetStatuses` in `pathprobe/path.go` to simply mark all links as `alive`

This got SCMP pings to work between two adjacent peering ASes and also the `bwtest` app could run successfully over the shortcut.

Given the lack of help and the insufficient documentation, I'm giving up beyond this point. Best of luck to anyone wishing to pursue this further.

**Comment by oncilla** [comment]
Hi @benthor

Sorry for not responding, I have been on vacation. 

Do you have a branch that we can take a look at?
Overall, the approach does not look that far off for getting a prototype working.
But it is hard to judge what is going on from this high level.

Also, always feel free to reach out to us on https://scionproto.slack.com/

**Comment by benthor** [comment]
Hi @oncilla,

See [this branch comparison](https://github.com/scionproto/scion/compare/master...benthor:scion:peering?expand=1). This is where I gave up.

With my changes, you can locally verify that peering is working between adjacent ASes by issuing the following:

```bash
make
./scion.sh topology -c topology/peering-test.topo
./scion.sh run
echo "0" | ./bin/scion ping -c 3 --sciond $(./scion.sh sciond-addr 112) -i 2-ff00:0:212,127.0.0.1
```
Sample output:
```
Available paths to 2-ff00:0:212:
2 Hops:
[ 0] Hops: [1-ff00:0:112 42>23 2-ff00:0:212] MTU: 1472 NextHop: 127.0.0.43:31018
4 Hops:
[ 1] Hops: [1-ff00:0:112 1>2 1-ff00:0:110 3>3 2-ff00:0:210 2>7 2-ff00:0:212] MTU: 1400 NextHop: 127.0.0.41:31014
Choose path: Resolved local address:
  127.0.0.1
Using path:
  Hops: [1-ff00:0:112 42>23 2-ff00:0:212] MTU: 1472 NextHop: 127.0.0.43:31018

PING 2-ff00:0:212,127.0.0.1:0 pld=0B scion_pkt=88B
96 bytes from 2-ff00:0:212,127.0.0.1: scmp_seq=0 time=1.035ms
96 bytes from 2-ff00:0:212,127.0.0.1: scmp_seq=1 time=972µs
96 bytes from 2-ff00:0:212,127.0.0.1: scmp_seq=2 time=915µs

--- 2-ff00:0:212,127.0.0.1 statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2.002079s
```

Child ASes of the peering ASes can not ping each other via the peering link:

```bash
echo "0" | ./bin/scion ping -i --sciond $(./scion.sh sciond-addr 113) 2-ff00:0:213,127.0.0.1 -c 3
```

Output:
```
Available paths to 2-ff00:0:213:
4 Hops:
[ 0] Hops: [1-ff00:0:113 3>3 1-ff00:0:112 42>23 2-ff00:0:212 3>3 2-ff00:0:213] MTU: 1472 NextHop: 127.0.0.49:31022
6 Hops:
[ 1] Hops: [1-ff00:0:113 3>3 1-ff00:0:112 1>2 1-ff00:0:110 3>3 2-ff00:0:210 2>7 2-ff00:0:212 3>3 2-ff00:0:213] MTU: 1400 NextHop: 127.0.0.49:31022
Choose path: Resolved local address:
  127.0.0.1
Using path:
  Hops: [1-ff00:0:113 3>3 1-ff00:0:112 42>23 2-ff00:0:212 3>3 2-ff00:0:213] MTU: 1472 NextHop: 127.0.0.49:31022

PING 2-ff00:0:213,127.0.0.1:0 pld=0B scion_pkt=112B

--- 2-ff00:0:213,127.0.0.1 statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 4.00166s
Error: no reply packet received


```

**Comment by oncilla** [comment]
Hi. Just checking in to say that we have not forgotten about this, and I will be provide feedback soon.

**Comment by oncilla** [comment]
Hi @benthor

I finally found time to give you some feedback on the peering link code. You can find it on a draft PR that I created based on your work (https://reviewable.io/reviews/scionproto/scion/4249)

The main reason the code did only work for direct neighbors was a misunderstanding of how the `Peer` flag in the info field works. You can find an explanation here: https://reviewable.io/reviews/scionproto/scion/4249#-NAkSrXY1ZDQyUtzl7md:-NAkSrXY1ZDQyUtzl7me:bssnr09

With small changes to the code, I got a fully functioning topology. See here: https://reviewable.io/reviews/scionproto/scion/4249#-NAkMRCmDy8kyUxEI_If:-NAkMRCmDy8kyUxEI_Ig:bp0jb2w

I think that can be used as a starting point for a pull request that would introduce this feature.
What still is missing are:
- Get `scion showpath` working with peering links
- Acceptance test cases: https://github.com/scionproto/scion/blob/master/tools/braccept/main.go
- Removing unnecessary code

**Comment by oncilla** [comment]
There was also a small bug in the path combinator that made everything even more confusing:

```diff
diff --git a/private/path/combinator/graph.go b/private/path/combinator/graph.go
index 3eb3e6b8a..e62ca9461 100644
--- a/private/path/combinator/graph.go
+++ b/private/path/combinator/graph.go
@@ -496,6 +496,9 @@ func calculateBeta(se *solutionEdge) uint16 {
 		}
 	} else {
 		index = len(se.segment.ASEntries) - 1
+		if index == se.edge.Shortcut && se.edge.Peer != 0 {
+			index++
+		}
 	}
 	beta := se.segment.Info.SegmentID
 	for i := 0; i < index; i++ {
```
This would lead to MAC verification failures in the data plane if the source AS was also the peering AS (i.e., first hop is already using the peering link) because the SegID was initialized with beta_i instead of beta_i+1
