### ISSUE TITLE
cppki: require segment lifetime fully covered by certificate chain

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#4286]
# Proposal

## Summary

Enforce the full lifetime of a segment/beacon is covered by the validity time of
at least one certificate chain.

### Problem

Currently, we do not enforce that the certificate chain that is used to verify a
segment is covering the full lifetime of the segment. Rather, we check that the
certificate chain is valid at verification time. This can cause issues if the
signing entity is failing to renew its certificate chains and issues segments
that with a lifetime that is not covered by any certificate chain. If the
segment life time is covered partially by a certificate chain, it can be verified
and will be inserted into segment/beacon storage. If there is a path segment request
that matches this segment, it will be part of the response. As soon as the
certificate chain expires, the segment is no longer verifiable. This causes
all future requests to fail with signature verification errors.

### How did we end up here?

Initially, there was an idea floating around that we could renew a certificate
chain for the same public key. In that world, having more lax verification rules
is nice, because the signing entity can create segments with longer lifetimes
even though its certificate chain has not been renewed yet. If the signing
entity succeeds to renew the certificate chain before the previous one expired,
the segment can be verified the whole time, without any issues.

However, this is mostly a theoretical advantage that comes with complexity
drawbacks. There are many more combinations between segment lifetime and
certificate chain validity time. The system also becomes a lot harder to reason
about. Furthermore, in practice each certificate chain authenticates a fresh
public key for better key hygiene.

## Solution

There is two sides to this problem. The signing entity and the relying party. To
make this a non-breaking change, we can start with adapting the behavior of
signing entity to ensure that no segments are created with lifetimes that are
not covered by a certificate chain. At a later stage, we can update relying
parties to not accept segments that are not covered by a certificate chain.

### Signing entity

The change to the signing entity is fairly small. When creating the hop fields
and peer fields for the AS entry, the expiration time should be chosen such that
the full lifetime is covered by the available certificate chain.

### Relying party

The change to the relying party is again fairly small. When a segment is
verified, the relying party additionally checks that the lifetime is fully
covered by the validity of the certificate chain. In theory, this is a breaking
change. However, in practice, segments that will be rejected by this change only
stem from cases where the certificate renewal fails.

## Alternatives

As an alternative, we could change the segment lookup and beaconing behavior to
filter out segments that can not be verified at the current time. This would
limit the effects of a missing certificate chain for a segment to one entity.

(Side-note: This check would be good even if we go with the proposal.)

However, this is not enough to behave correctly. Entities need to proactively
fetch certificate chains to fill in the gaps, as they might not learn the new
certificate chains passively. This is a lot of additional complexity that is
currently not implemented and will be hard to get right. It is also hard to
justify this additional complexity if in practice that feature will never be
used due to the rotated private keys on every certificate.

**Comment by matzf** [comment]
This sounds good to me.

#### Alternative 2: certificate validity only checked for path segment signature timestamp

Instead of checking that the certificate chain is valid at verification time, we only enforce that the certificate chain is valid at the signature timestamp. 
This provides a solution to the problems described above, as a the validation of the segment is no longer dependent on the verification time. Intermittent issues to renew certificates do not affect the segment validation.
This is a change in the semantics. Currently, the lifetime of path segments is restricted to the lifetime of AS certificate chain(s). With this alternative proposal, only the time during which path segments can be _issued_ is restricted.

Graphically (although perhaps it's almost too obvious):
![path-seg-cert-lifetime excalidraw](https://user-images.githubusercontent.com/42933359/199943626-9fef368a-abfa-497a-ab11-9bf8ffe7f146.png)

The path segment with the orange exclamation point is valid under these new semantics, but would be rejected under the current semantics or the proposal above.


**Implications**

- ASes can create path segments that can be valid for the maximum path segment lifetime (~24 hours) after an AS certificate expires.
- when an AS ceases to exist, it's identifier cannot be reassigned immediately. This seems unproblematic as we have a very large number of ASIDs. Also, there are probably other reasons why its good not to reassign an ASID immediately.
- when an AS was temporarily compromised, path segments issued by the attacker remain valid for longer than the certificate. To recover from the compromise, the operators of the AS will need to change to new hop validation keys, which invalidates all  old path segments in the dataplane; packets using older paths will be dropped (with SCMP error). This will have negative performance implications for end hosts, as they will individually have to discover that the paths are "revoked".
  Note that this will happen happen either way, but this alternative proposal increases the potential duration for this performance degradation.

**Advantage**

I've been working on a proposal to support overlapping ISDs. One idea for this is that the AS Entries in path segments could contain multiple signatures, one for each ISD that an AS is part of.
In this setup with overlapping ISDs, ASes would be juggling multiple certificates with possibly very different lifetimes. The stricter requirements on the certificate lifetime here would restrict the lifetime of announced paths to the intersection of the certificate lifetimes. This could become quite complicated and so it would be appealing to only require certificate validity at the time of the signature.

**Comment by matzf** [comment]
Discussion in the proposal review meeting; generally all in favor of this proposal. It's not quite clear yet which approach is preferred; the "Alternative 2" variant described above would appear to be simpler to implement as it does not require changes to the control plane certificate request messages. However, it does seem to imply that path segments cannot be revoked with a TRC update. It's a bit unclear whether this would practically change anything, because the TRC grace period is likely on the same order or magnitude as a path segment lifetime anyway.

**Comment by matzf** [comment]
What about variant 2.1 to "fix" allowing path segment revocation by TRC update; we check that the certificate is valid at the issuing time for the path segment (as described above) and _additionally_ we require that the TRC of the AS certificate is active at  validation time.
As long as the grace period for the TRC updates is chosen long enough, path segments would not be considered revoked by a TRC update.

**Comment by oncilla** [comment]
I think variant 2.1 should work without any issues.

**Comment by matzf** [comment]
I've just updated #4293: the variant affected by this proposal (Variant 3) seemed the least likely option anyway, so I've removed this. Thus, I no longer have any objections against the original proposal. @oncilla, as you still prefer the original proposal, lets go with that.

**Comment by matzf** [comment]
Going forward, we're **likely** going **accept** this proposal. The final comment period starts now, and unless there are objections during this period, the proposal will be marked as accepted.
