### ISSUE TITLE
## Define router performance metrics reproducible in (at least) a given developer env

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4409]

**Comment by jiceatscion** [comment]
Brief design:

In this phase, we're not trying to create performance diagnostic instrumentation, only measure the end-2-end performance. Ideally, for each packet processed, we'd like to collect the following metrics:

* Packet category: processing type (such as transiting, incoming, outgoing) and size.
* Total CPU cycles (or time) expanded.
* IOwait cycles (or time) expanded.

The resolution of the IOWait time in linux is coarse (10ms), so we cannot measure it with any kind of precision for a single packet. As a result we have to average an accumulated value over a larger number of packets that we count. This, in turn, means that we cannot attribute IOWait time to a specific packet category, unless there is only one category processed during the measurement (or unless we do several runs with different mixes and a linear regression - not any easier and less precise). Regarding CPU time, we have a hi-res counter so, we could accumulate it on a packet-per-packet basis. We try both and compare.

Therefore for a given measurement run we will collect the following metrics (using prometheus):
* Accumulated Packet count by (type, size)
* Accumulated size by (type, size)
* Accumulated Packet-processing CPU time by (type, size) (for a given packet we add to the metric the difference between CLOCK_CPU_TIME before and after processing)
* Process-wide CPU time (CLOCK_CPU_TIME_ID for example)
* Process-wide IOWait time (/proc/pid/stat:delayacct_blkio_ticks)

At the end of the measurement we can calculate:
* Average CPU time per packet by (type, size)
* Process-wide average CPU time per packet (all categories averaged) - for comparison of precision with the per-packet counter; both have their weakness
* Average CPU time per payload byte by (type, size)
* Average CPU time per payload byte by type - all packet sizes averaged
* Average process-wide IOWait time per packet (all categories averaged since we have no other metric)

Due to the limitation in IOWait time measurement, we'd typically run benchmarks with only one packet category at a time (as much as possible). There would be likely a small number of other packets processed. We just average them with the rest and accept the small error introduced.

**Comment by jiceatscion** [comment]
Progress report.
Metrics updated with traffic type and packet size labels.

Next, if possible, per-packet CPU time and iowait.

**Comment by jiceatscion** [comment]
Update:

The iowait metric turned out to be useless as it doesn't include sleep time, which is what an IO wait looks like when done by Go through async IO. The main use of that metric was to be able to compare the amount of work accomplished to the amount of CPU actually available (as opposed to time spent un-scheduled due to competing processes). As it turns out, the kernel is kind enough to give us just that information: that is, the process's cummulative runnable time. It is available per-thread in /proc/<pid>/schedstat. This is a much better source of information than iowait time, especially considering that there's no way to get a process' sleep time separately.

So, I added metrics that report that.

It may also be that this metric is of high-enough resolution that we could collect-it per-packet. But that is yet to be verified.

**Comment by jiceatscion** [comment]
On last update on this topic. I'm giving up on packet-per-packet CPU metering too because I don't think it is possible to attribute the CPU usage expanded between a given packet's ingress and egress to that particular packet. So, we'd get no better information than averaging. What we could do is to look at the real-time clock, and so calculate a packet-per-packet latency. That would be useful once we start doing fine-grain optimizations, but not now. So...mater shelved.

For now, I'll make a PR with the metrics I've added.
