### ISSUE TITLE
## Create router benchmark automation, with performance data collection

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4410]

**Comment by jiceatscion** [comment]
This has started. Rough plan:

* Create end2end-style test program that generates a router load (in a specific packet size class):
  * The test generates load of a given packet size and number between every host pair in the available topology.
  * Each kind of load test comes with a custom topology such that exercising all pairs produces a relevant traffic mix.
* Add automation to run the test and Collect and report packets/available-cpu-seconds and bytes/available-cpu-seconds:
  * Run the test over an add-hoc topology where each type of traffic (incoming/outgoing/local/transit) is processed by one identified router.
  * At the end of the test collect metrics for each traffic type and  the relevant size class between two TBD points in time (eg. 1 second after start and 1 second before end), and calculates and logs the average packet/available-cpu-seconds and byte/per-available-cpu-seconds.
* Add acceptance test that runs the above and compares the result with some expectation. Expectations (and the resulting success/failure of the test) would be dependent of the platform where the test is run. So, this may be a CI-only test.
* Cherry on the cake: Extrapolate some approximate abstract, platform independent, value, and have expectations for that, instead of the real numbers.

The first point is done.
