### ISSUE TITLE
[acceptance tests] HP test

### ISSUE THREAD

**Issue by JordiSubira** [scionproto/scion#4474]
The following code snippet https://github.com/scionproto/scion/blob/master/acceptance/hidden_paths/test.py#L117-L119 is executed in two logic phases of the acceptances test, i.e., setup and run. If we run the test with `bazel test  //acceptance/hidden_paths:all` it works well, however, if we run each test phase manually, i.e., `bazel run //acceptance/hidden_paths:test_setup` and `bazel run //acceptance/hidden_paths:test_run`, it fails. I guess, a simple solution would be to move
```
self.await_connectivity()
self._server.shutdown()  # by now configuration must have been downloaded everywhere
```
into  `setup_prepare()`

**Comment by oncilla** [comment]
The right fix is to move it to the setup phase, correct.

However, the setup prepare usually only sets up the required files.
Only in the setup_start phase the containers are actually started and pull the configuration.

The mentioned snippet should be moved to this phase instead of the setup_prepare.

**Comment by JordiSubira** [comment]
Yes, indeed I mixed the names up, setup_start is what I meant. Thanks for clarifying!
