### ISSUE TITLE
Running mininet with SCION

### ISSUE THREAD

**Issue by vanvantong** [scionproto/scion#4661]
Hello alls,

I am a newbie about SCION architecture. I would like to run mininet with SCION architecture. I already the description on "SCION: A Secure Internet Architecture", but it is not clearly explained. Can you show me how to do this?
Thank you in advance!

**Comment by JordiSubira** [comment]
Hello @vanvantong mininet support was removed long ago here https://github.com/scionproto/scion/issues/2171. The book version you are looking at is unfortunately quite outdated and it is not really useful for keeping it up with developments in the OS implementation. The main technical documentation for SCION can be found at https://docs.scion.org/en/latest/index.html.

You can achieve something very similar spawning locally some docker containers. For this you can follow [Running SCION locally](https://docs.scion.org/en/latest/dev/run.html#running-scion-locally) (please notice the prerequisites for this, mainly [Setting up the devolpment environment](https://docs.scion.org/en/latest/dev/setup.html)). The example command `./scion.sh topology -c topology/tiny.topo` generates the artificats for running the SCION network as user-space process. However, you can add the `-d` flag to generate Docker artifcats instead, i.e.: `/scion.sh topology -c topology/tiny.topo -d`. 

Additionally, there's also support for the seed emulator https://github.com/seed-labs/seed-emulator/tree/master/examples/scion, which may also be of interest for you. 

For following up on this, I invite you to use our [Elements channel](https://matrix.to/#/#dev:matrix.scion.org). There you can have more interactive feedback.

Best!

**Comment by vanvantong** [comment]
Hell Jordi Subira,

Thank you for your quick response.
I would like to run experiments to evaluate the performance of several applications on SCION architectures (e.g., video streaming using QUIC, etc.). When installing SCION, I found out that SCION supports QUIC via quic-go. I implemented video streaming using QUIC with mininet. Now, I would like to repeat this experiment with SCION. Does SCION support to interact with CLI like mininet?
Are there any options to estimate network parameters of links in the topology of SCION (e.g., delay, loss, link utilization, etc.)?

**Comment by JordiSubira** [comment]
For this, I recommend you to use the seed emulator. More specifically, it may be of interest for you this example that allows to define link properties https://github.com/seed-labs/seed-emulator/tree/master/examples/scion/S06-scion-link-properties. In the Python script you can define link properties as explained in the description. In order to compile and run the docker containers, you can follow the simple instructions provided by seed maintainers on the [README](https://github.com/seed-labs/seed-emulator) for the setup and running steps) file, all examples are run the same way.

As mentioned, the seed emulator is based on Docker, so you can interact with the containers as usual in Docker. Each SCION infrastracture component, i.e., SCION Border Router (BR) and SCION Control Service (CS). The CS node already has a SCION endhost stack running (i.e., SCION daemon and SCION shim dispatcher). You can either upload your SCION application to it and run it from within, or create a separate container and run your application from there.

I would like to clarify a bit though to avoid confusion in the aspect of SCION support for QUIC. We have SCION support for QUIC indeed, meaning that we have a QUIC implementation that uses SCION underneath. Currently we have a Go implementation https://github.com/netsec-ethz/scion-apps/blob/master/pkg/pan/quic_listen.go, i.e., you can use by importing "github.com/netsec-ethz/scion-apps/pkg/pan". In order for your application to use **native** QUIC/SCION you have to use the PAN library. 

Another possibility is to the [SCION Internet Gateway](github.com/netsec-ethz/scion-apps/pkg/pan) (SIG) in your deployment. The SIG tunnels IP traffic over SCION, i.e., hosts in a certain subnet (configurable) route their IP traffic via the SIG, which upon receiving the traffic encapsulates it in SCION packets. It there a [branch](https://github.com/Bruol/seed-emulator/blob/master/examples/scion/S08-scion-ip-gateway/scion_ip_gateway.py) that deploys also those SIGs.

I am now closing this issue, please follow up on one of these two channels:
- Email: [scionlab-admins@sympa.ethz.ch](mailto:scionlab-admins%40sympa.ethz.ch)
- Matrix: https://chat.scion.org/ (recommended, quicker feedback).

**Comment by vanvantong** [comment]
Hello Jordi Subira,

Can you add my email to Slack of SCION Proto?
My email: vantv@soict.hust.edu.vn
I really want to get updates on SCION architecture.
Thank you.
